icon: ':simple-plex:'
cit:
  mode: screenshot
  port: 8181
  health: /status
  wait: 300

build:
  variants:
    - tag: latest
      containerfile: Containerfile
      default: true
    - tag: pkg
      containerfile: Containerfile.pkg
    - tag: pkg-latest
      containerfile: Containerfile.pkg
      args:
        BASE_VERSION: "15-latest"
